apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "django.fullname" . }}
  namespace: orihime
  labels:
    app: {{ include "django.fullname" . }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /var/lib/{{ include "django.fullname" . }}
