apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django.fullname" . }}
  namespace: orihime
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  selector:
    matchLabels:
      app: {{ include "django.fullname" . }}
